### ISSUE TITLE
Support Secure Files

### ISSUE THREAD

**Issue by zlannin** [Caphyon/advinst-vsts-task#10]
First I wanted to say thanks for this tool, I was able to get it up and running with little work. 

While working with the task I felt it could really use the ability to select your pfx certificate from secured files like [code signing task](https://marketplace.visualstudio.com/items?itemName=stefankert.codesigning) and provide the password!

**Comment by burcadoruciprian** [comment]
Hi,

Sorry for the very late reply. You can actually use secure files right now. Here is how this will work:

- Add the certificate to Secure Files library
- Before the advinst task, add a **Download Secure File** task and select you certificate
- Configure the advinst task and add the following command in **Command Line Arguments** field `SetDigitalCertificateFile -file $(certFilePfx.secureFilePath)` (_certFilePfx_ is the reference name you configure in the download task)

Thats it.
