### ISSUE TITLE
Changing the aipOutputFolder field type can break some releases

### ISSUE THREAD

**Issue by Gimly** [Caphyon/advinst-vsts-task#12]
We've experienced some of our release break with the recent change in the aipOutputFolder change from filePath to string.

The filePath field type supports having path with forward (/) or backward (\) slash and makes it compatible. But with the change to string, it fails if there are some forward slashes and seems to only support backslash.

It was a quick fix on our side, replacing the forward with backslash, but I wanted to give you a heads up that this change might break some of your user's pipelines.

**Comment by Chicoo** [comment]
Could it be that changing the type to string the path is no longer resolved properly if it is a relative path:

e.g. /output/installer was resloved to c:\agent\_work\x\output\installer

But now it keeps pointing to /output/installer.
An absolute path will not work as the output needs to be copied to a location in the repo.

**Comment by Gimly** [comment]
@Chicoo That's true, it might also be another source of failure, but in our case it was already an absolute path, it's just that it didn't like the mix between / and \.

**Comment by burcadoruciprian** [comment]
Hi,

The "Output Folder" was indeed changed. It used to be relative to the checkout location which caused crashes in release pipelines. Now you need to specify a complete folder path in that field. You can use Azure DevOps variables to specify various root folders

**Comment by burcadoruciprian** [comment]
Hey,

We have fixed this issue in the 2.0.5 version. Things should work as they did before. Let us know if you encounter any more issues.
