### ISSUE TITLE
Correct way to use  AdvancedInstaller@2 - task with floating license?

### ISSUE THREAD

**Issue by DrCopyPaste** [Caphyon/advinst-vsts-task#14]
Hello,

what is the correct way to use this task together with a floating license key.
Trying to manually enter that license key in that task as parameter 'advinstLicense' results in:

##[error]Failed to register Advanced Installer. Error: Unable to register Advanced Installer. A floating license can be used only by the floating license server.

I would like to let that task be run in house using a custom agent that has access to our network and hence reach the license server, but how would I let 'AdvancedInstaller@2'-Task know about it?

I do not see extra parameters to pass a license server-  what am I missing?

**Comment by radu-dnl-caphyon** [comment]
> Hello,
> 
> what is the correct way to use this task together with a floating license key.
> Trying to manually enter that license key in that task as parameter 'advinstLicense' results in:
> 
> ##[error]Failed to register Advanced Installer. Error: Unable to register Advanced Installer. A floating license can be used only by the floating license server.
> 
> I would like to let that task be run in house using a custom agent that has access to our network and hence reach the license server, but how would I let 'AdvancedInstaller@2'-Task know about it?
> 
> I do not see extra parameters to pass a license server- what am I missing?

Hi,

Unfortunately our Advanced Installer build task does not support registering with a floating license, this is a limitation of our build task.

Could you please write us a short email at support@advancedinstaller.com including your floating license key? We will help you with a workaround for this limitation.

All the best,
Daniel - Advanced Installer Support Team

**Comment by DrCopyPaste** [comment]
Thanks for the response, sorry for my late reply - will do.
I will comment again if that solved my case.

**Comment by DrCopyPaste** [comment]
The solution worked out with Support works well.
Thanks again for the help.
