### ISSUE TITLE
Not possible to build installers since last 2.0.9 versions

### ISSUE THREAD

**Issue by sprudh** [Caphyon/advinst-vsts-task#16]
Hello,

You add in the release notes:
" We no longer support versions of Advanced Installer that are more than two years old. Please check the [release history](https://www.advancedinstaller.com/version-history.html) to pick a compatible version."

But it's not possible to choose the version used in the azure devops task, you can only choose major version for exemple 2.x.
So the pipeline take the 2.0.9 that contains this breaking change, why you didn't increment the Major version instead ?
We can't release to our customers any minor versions now.
Please revert this change into a 2.0.10 version and create a 3.0 version with this breaking change.

Best Regards
Sylvain Prudhon
Software Team Leader at Rollomatic SA

**Comment by joeylemmens** [comment]
Hi,

We have exact the same problem and this is blocking our release. This should have been as suggested a major release of the Devops Task. So please handle this with the highest priority.

We have the following issue:

```
[error]Invalid Advanced Installer version configured. Minimum required version: 18.3. Configured version: 13.5.
```

Kind regards,

Joey Lemmens

**Comment by knabb** [comment]
So as far as I can tell this change just breaks a good number of build pipelines, including mine. And I don't see a way to work around it. Would have happily paid whatever license cost to avoid this. We freeze the version of AI so as to avoid constant regression on AI version upgrades.

**Comment by andrewmolyneux** [comment]
I have the same problem and it's really hurting me - I'm supposed to be doing a final build this week and my tester is on vacation so I absolutely can't be updating a major build tool at this point. Just a thought, but it should be possible (albeit a hassle) to clone this repo, build one's own private copy of the extension and use that instead after removing the "version age" check...
I have an open case with Caphyon support but if that doesn't work out, the above is my plan B.

**Comment by andrewmolyneux** [comment]
Update: cloning the repo and removing the version check didn’t help - looks like their license server is also refusing to issue CI licenses to versions that are “too old” so that’s it, I’m out of options.

**Comment by Admir-H** [comment]
We have the same issue!

**Comment by nathan-swannet** [comment]
Exactly the same issue here - pls revert the change and introduce this in a major version instead.
Thanks!

**Comment by ajberry** [comment]
We no longer support versions of Advanced Installer that are more than two years old. Please check the [release history]

From the notes of the latest commit. Doing this with no notice is ridiculous

**Comment by BogdanMitrache** [comment]
Hello,

I am sorry for the problems, I've incorrectly evaluated the impact of these changes. We have a monthly release cycle and we understand how disrupting this change was for you. This was never our intention.

**We will release a new minor update in the next 12 hours**, this will revert the changes and get your build back and running.

All the changes included in 2.0.9 will be included in a major update(3.0) later this summer, giving everyone more time to prepare for this change.

Bogdan Mitrache
Head of Product at Advanced Installer

**Comment by ajberry** [comment]
Thanks for the quick response :)

**Comment by sprudh** [comment]
Thank you !

**Comment by BogdanMitrache** [comment]
> Update: cloning the repo and removing the version check didn’t help - looks like their license server is also refusing to issue CI licenses to versions that are “too old” so that’s it, I’m out of options.

@andrewmolyneux This happens because you are using a version of Advanced Installer that is almost 7 years old. Sometime in the last 4 years there was a breaking change in our command line registration options and until version 2.0.9 we maintained both options to register Advanced Installer, but this was registration capapibility was removed because all the versions of the last 2 years work with the new registration command line.

We will revert this too until version 3.0 is released.

**Comment by nathan-swannet** [comment]
Thanks!!

**Comment by ajberry** [comment]
Will version 2.* still be available for existing pipelines once 3.0 is released?

**Comment by BogdanMitrache** [comment]
@ajberry we are investigating this option.  From what we can see at the moment the Azure DevOps marketplace doesn't provide support to host multiple versions of the same extension.

Do you need version 2.* of our extension for a hosted version of Azure DevOps or for the cloud?

Also, version 3.* will allow you to run any version of Advanced Installer, but now older than 18.3. Why would you prefer using an older version (which most likely does not include our latest OS compatibility and security updates)?

**Comment by ianhaydenexp** [comment]
Would like to add that this broke our pipelines too. 
I'd like to vote for retaining existing functionality/compatibility in the future for existing versions.
We don't want to have to upgrade AI or the AzDo plugin for features/fixes we don't require.

**Comment by ajberry** [comment]
> @ajberry we are investigating this option. From what we can see at the moment the Azure DevOps marketplace doesn't provide support to host multiple versions of the same extension.
> 
> Do you need version 2.* of our extension for a hosted version of Azure DevOps or for the cloud?
> 

Currently when I add an Advanced Installer Build task in my pipeline, I can select from 1.* and 2.* for the Task Version. I would presume when you release 3.* then we can still select 2.* which will still work once the revert happens? 

> Also, version 3.* will allow you to run any version of Advanced Installer, but now older than 18.3. Why would you prefer using an older version (which most likely does not include our latest OS compatibility and security updates)?

We have many installers that have been built with 14.8, so it's more understanding if we need to update/test as it will take a reasonable amount of time to do this, so we don't affect customer releases.

**Comment by BogdanMitrache** [comment]
A new release (2.11) is now available. 

Please consider upgrading your version of Advanced Installer in the following two months to avoid a similar situation when we'll release version 3.0.

**Comment by sprudh** [comment]
The new version fix the issue, thanks !

**Comment by sprudh** [comment]
I close the issue, it's work in our pipelines.
