### ISSUE TITLE
AdvInstExtTasks.Targets was not found error on team services

### ISSUE THREAD

**Issue by ronnelsantiago** [Caphyon/advinst-vsts-task#3]
first off how would u actually install AI on team services? 

Error MSB4019: The imported project "C:\Program Files (x86)\MSBuild\Caphyon\Advanced Installer\AdvInstExtTasks.Targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.

**Comment by burcadoruciprian** [comment]
To install AI use the [Advanced Installer Tool Installer](https://marketplace.visualstudio.com/items?itemName=caphyon.AdvancedInstallerTool) task
