### ISSUE TITLE
Possible to use in VSTS online

### ISSUE THREAD

**Issue by oneillci** [Caphyon/advinst-vsts-task#4]
Is is possible to use the Advanced Installer package in visual studio online so we can create a build definition that has an Advanced Installer artefact?

**Comment by fjch1997** [comment]
You can install and activate Advanced Installer using a powershell script

**Comment by burcadoruciprian** [comment]
We are working on creating a tool installer task which will allow you to deploy and use Advanced Installer with VS online.

**Comment by burcadoruciprian** [comment]
Hi, 

The new Tool Installer extension is now available for use. It will deploy advinst on the host machine.
https://marketplace.visualstudio.com/items?itemName=caphyon.AdvancedInstallerTool
