### ISSUE TITLE
VSTS Build issue - "AdvancedInstaller.com" is not recognized

### ISSUE THREAD

**Issue by KT324** [Caphyon/advinst-vsts-task#5]
I've setup my Build Definition to match the demo, with a task for the AdvancedInstaller Tool Installer, followed by the Build tool task. I'm getting the following error:

![image](https://user-images.githubusercontent.com/29666975/30751190-9a9c878c-9f86-11e7-9dda-712b6d470c57.png)

**Comment by burcadoruciprian** [comment]
Thanks for you feedback.  The problem was actually with the [Advanced Installer Tool Installer](https://marketplace.visualstudio.com/items?itemName=caphyon.AdvancedInstallerTool) and it is fixed now. Please update and let me know it there are any more issues.
