### ISSUE TITLE
Error in Advanced Installer task don't stop build

### ISSUE THREAD

**Issue by marceloavf** [Caphyon/advinst-vsts-task#6]
Failed to execute Advanced Installer task don't stop the build and gives it a success definition. Even with `Continue on Error` unchecked 

Advanced Installer v14.5.2
![image](https://user-images.githubusercontent.com/5435657/34613850-75ee79e4-f216-11e7-98d1-8dbdd4527c56.png)

**Comment by burcadoruciprian** [comment]
Fixed in 1.2.4 release
